`timescale 1ns/1ps
// ─── FalconSign Top-Level Integration Test with External Key ───
//
// Loads a complete Falcon-512 key (B matrix + LDL tree + public key h)
// generated by gen_falcon_hw_key.c from the official reference
// implementation, then runs the full signing pipeline.
//
// The test message "FALCON_SIGN_TEST_MSG_V1.0______" (hardcoded in RTL)
// matches the message used during key generation, so the expected
// signature values should match modulo RNG differences.
//
// Usage:
//   iverilog -o tb_fullkey.vvp tb_falconsign_top_fullkey.v \
//       ../rtl/falcon/*.v ../rtl/common/*.v
//   vvp tb_fullkey.vvp

module tb_falconsign_top_fullkey;

    localparam [15:0] REG_CR     = 16'h0000;
    localparam [15:0] REG_SR     = 16'h0004;
    localparam [15:0] REG_CFG    = 16'h0008;
    localparam [15:0] REG_MEM_HI = 16'h000C;

    // ─── Hardware memory map ───
    localparam integer LAYOUT_T0_BASE   = 0;
    localparam integer LAYOUT_T1_BASE   = 512;
    localparam integer LAYOUT_TREE_BASE = 1024;
    localparam integer LAYOUT_Z0_BASE   = 3840;
    localparam integer LAYOUT_Z1_BASE   = 4352;
    localparam integer LAYOUT_B00_BASE  = 4864;
    localparam integer LAYOUT_B01_BASE  = 5376;
    localparam integer LAYOUT_B10_BASE  = 5888;
    localparam integer LAYOUT_B11_BASE  = 6400;
    localparam integer LAYOUT_SIG_BASE  = 6912;
    localparam integer LAYOUT_C_INT_BASE = 7424;
    localparam integer LAYOUT_H_BASE    = 7456;
    localparam integer LAYOUT_S1_BASE   = 7488;

    localparam integer FALCON_N = 512;
    localparam integer N_WORDS  = 512;   // RTL complex words per B polynomial

    reg         clk;
    reg         rst_n;

    // Bus interface
    reg         bus_cs;
    reg         bus_wr;
    reg  [15:0] bus_addr;
    reg  [31:0] bus_wdata;
    wire [31:0] bus_rdata;
    wire        bus_ready;
    wire        bus_irq;
    wire        busy;
    wire        done;
    wire        fail;
    wire [7:0]  status;

    falconsign_top #(.ADDR_W(13), .LEVEL_W(4), .INDEX_W(10)) dut (
        .clk(clk), .rst_n(rst_n),
        .bus_cs(bus_cs), .bus_wr(bus_wr),
        .bus_addr(bus_addr), .bus_wdata(bus_wdata),
        .bus_rdata(bus_rdata), .bus_ready(bus_ready),
        .bus_irq(bus_irq),
        .busy(busy), .done(done), .fail(fail), .status(status)
    );

    // ─── Clock & Reset ───
    initial begin
        clk   = 1'b0;
        rst_n = 1'b0;
        #30 rst_n = 1'b1;
    end
    always #5 clk = ~clk;

    // ─── Read hex file into temporary array, then load to memory ───
    reg [255:0] hex_buf [0:4095];  // enough for up to 4096 words
    reg [255:0] s1_expected [0:31];
    reg [255:0] s2_expected [0:31];
    reg [255:0] t0_initial  [0:N_WORDS-1];
    reg [255:0] t1_initial  [0:N_WORDS-1];
    integer     hex_nwords;
    integer     i;
    integer     cmp_idx;
    integer     s1_mismatch;
    integer     s2_mismatch;
    integer     fs_mu_z0_mismatch;
    integer     fs_mu_z1_mismatch;
    integer     fs_mu_first_z0;
    integer     fs_mu_first_z1;

    task load_hex_to_mem;
        input [1024*8-1:0] filename;
        input integer       base_addr;
        input integer       num_words;
        integer fd, n, addr;
        reg [255:0] word;
        begin
            $display("Loading %s -> addr %0d (%0d words)...", filename, base_addr, num_words);
            fd = $fopen(filename, "r");
            if (fd == 0) begin
                $display("ERROR: Cannot open %s", filename);
                $finish;
            end
            for (addr = 0; addr < num_words; addr = addr + 1) begin
                n = $fscanf(fd, "%h\n", word);
                if (n != 1) begin
                    $display("ERROR: Short read at addr %0d of %s (n=%0d)", addr, filename, n);
                    $finish;
                end
                case ((base_addr + addr) & 3)
                    0: dut.u_mem.bank0[(base_addr + addr) >> 2] = word;
                    1: dut.u_mem.bank1[(base_addr + addr) >> 2] = word;
                    2: dut.u_mem.bank2[(base_addr + addr) >> 2] = word;
                    default: dut.u_mem.bank3[(base_addr + addr) >> 2] = word;
                endcase
            end
            $fclose(fd);
            $display("  Loaded %0d words OK", num_words);
        end
    endtask

    function [255:0] peek_mem_word;
        input integer word_addr;
        begin
            case (word_addr & 3)
                0: peek_mem_word = dut.u_mem.bank0[word_addr >> 2];
                1: peek_mem_word = dut.u_mem.bank1[word_addr >> 2];
                2: peek_mem_word = dut.u_mem.bank2[word_addr >> 2];
                default: peek_mem_word = dut.u_mem.bank3[word_addr >> 2];
            endcase
        end
    endfunction

    task poke_mem_word;
        input integer word_addr;
        input [255:0] word;
        begin
            case (word_addr & 3)
                0: dut.u_mem.bank0[word_addr >> 2] = word;
                1: dut.u_mem.bank1[word_addr >> 2] = word;
                2: dut.u_mem.bank2[word_addr >> 2] = word;
                default: dut.u_mem.bank3[word_addr >> 2] = word;
            endcase
        end
    endtask

    task preload_bypass_z_eq_t;
        integer k;
        begin
            for (k = 0; k < N_WORDS; k = k + 1) begin
                poke_mem_word(LAYOUT_Z0_BASE + k, peek_mem_word(LAYOUT_T0_BASE + k));
                poke_mem_word(LAYOUT_Z1_BASE + k, peek_mem_word(LAYOUT_T1_BASE + k));
            end
            $display("BYPASS_FS preload: copied t0/t1 into z0/z1 (%0d words each)", N_WORDS);
        end
    endtask

    // ─── Direct bus operations ───
    task bus_write;
        input [15:0] addr;
        input [31:0] data;
        begin
            @(posedge clk);
            bus_cs    <= 1'b1;
            bus_wr    <= 1'b1;
            bus_addr  <= addr;
            bus_wdata <= data;
            @(posedge clk);
            bus_cs    <= 1'b0;
            bus_wr    <= 1'b0;
            bus_addr  <= 16'd0;
            bus_wdata <= 32'd0;
            wait (bus_ready);
            @(posedge clk);
        end
    endtask

    task bus_read;
        input  [15:0] addr;
        output [31:0] data;
        begin
            @(posedge clk);
            bus_cs    <= 1'b1;
            bus_wr    <= 1'b0;
            bus_addr  <= addr;
            bus_wdata <= 32'd0;
            @(posedge clk);
            bus_cs    <= 1'b0;
            bus_addr  <= 16'd0;
            wait (bus_ready);
            data = bus_rdata;
            @(posedge clk);
        end
    endtask

    // ─── Phase tracking ───
    function [127:0] phase_name;
        input [3:0] p;
        case (p)
            4'd0: phase_name = "SI_Idle";
            4'd1: phase_name = "SH_SeedHash";
            4'd2: phase_name = "HP_HashToPoint";
            4'd3: phase_name = "FC_FFT";
            4'd4: phase_name = "FS_ffSampling";
            4'd5: phase_name = "VD_BhatMul";
            4'd6: phase_name = "IV_IFFT";
            4'd7: phase_name = "FI_FprToInt";
            4'd8: phase_name = "N1_NTT";
            4'd9: phase_name = "RC_RejCheck";
            4'd10: phase_name = "CN_Compress";
            4'd11: phase_name = "EN_Encode";
            4'd12: phase_name = "OU_Output";
            4'd13: phase_name = "SD_SendDone";
            default: phase_name = "UNKNOWN";
        endcase
    endfunction

    reg [3:0]  prev_st;
    reg [31:0] total_cycle;
    reg [31:0] restart_cnt;
    reg [31:0] fs_task_issues;
    reg [31:0] fs_task_done;
    reg [31:0] fs_task_fail;
    reg [31:0] sample_cmds;
    reg [31:0] sample_rsps;
    reg [31:0] fs_sample_task_trace;
    reg [3:0]  completed_phases [0:15];
    integer    phase_idx;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            prev_st    <= 0;
            total_cycle <= 0;
            restart_cnt <= 0;
            fs_task_issues <= 0;
            fs_task_done <= 0;
            fs_task_fail <= 0;
            sample_cmds <= 0;
            sample_rsps <= 0;
            fs_sample_task_trace <= 0;
            for (phase_idx = 0; phase_idx < 16; phase_idx = phase_idx + 1)
                completed_phases[phase_idx] = 0;
        end else begin
            total_cycle <= total_cycle + 1;
            if (dut.ts_task_valid && dut.ts_task_ready) fs_task_issues <= fs_task_issues + 1;
            if ($test$plusargs("FS_TRACE_TASKS") && dut.ts_task_valid && dut.ts_task_ready && fs_task_issues < 40) begin
                $display("  FS_TASK[%0d]: op=%0d level=%0d index=%0d src0=%0d src1=%0d dst=%0d aux=%02x",
                    fs_task_issues, dut.ts_task_word[67:64], dut.ts_task_word[63:60], dut.ts_task_word[59:50],
                    dut.ts_task_word[49:36], dut.ts_task_word[35:22], dut.ts_task_word[21:8], dut.ts_task_word[7:0]);
            end
            if (dut.ts_task_valid && dut.ts_task_ready && dut.ts_task_word[67:64] == 4'd3
                && (fs_sample_task_trace < 8 || (dut.ts_task_word[21:8] >= LAYOUT_Z0_BASE && dut.ts_task_word[21:8] < (LAYOUT_Z0_BASE + 8)))) begin
                $display("  FS_SAMPLE_TASK[%0d]: level=%0d index=%0d src0=%0d src1=%0d dst=%0d",
                    fs_sample_task_trace, dut.ts_task_word[63:60], dut.ts_task_word[59:50],
                    dut.ts_task_word[49:36], dut.ts_task_word[35:22], dut.ts_task_word[21:8]);
                fs_sample_task_trace <= fs_sample_task_trace + 1;
            end
            if (dut.ts_task_done) fs_task_done <= fs_task_done + 1;
            if (dut.ts_task_fail) fs_task_fail <= fs_task_fail + 1;
            if (dut.fe_sz_cmd_valid && dut.fe_sz_cmd_ready) sample_cmds <= sample_cmds + 1;
            if (dut.sz_rsp_valid) sample_rsps <= sample_rsps + 1;

            if (dut.st != prev_st) begin
                $display("[T=%0d cy=%0d] PHASE: %s -> %s",
                    $time, total_cycle,
                    phase_name(prev_st), phase_name(dut.st));
                completed_phases[prev_st] = 1;
                prev_st <= dut.st;

                if (dut.st == 4'd1 && (prev_st == 4'd9 || prev_st == 4'd7)) begin
                    restart_cnt <= restart_cnt + 1;
                    $display("  *** RESTART #%0d ***", restart_cnt + 1);
                end
                if (dut.st == 4'd13) begin
                    $display("=== SIGNING COMPLETE: total_cycles=%0d restarts=%0d ===",
                        total_cycle, restart_cnt);
                end
                if (prev_st == 4'd4 && dut.st == 4'd5) begin
                    $display("  FS z snapshot:");
                    fs_mu_z0_mismatch = 0;
                    fs_mu_z1_mismatch = 0;
                    fs_mu_first_z0 = -1;
                    fs_mu_first_z1 = -1;
                    if ($test$plusargs("FS_SAMPLE_MU")) begin
                        for (phase_idx = 0; phase_idx < N_WORDS; phase_idx = phase_idx + 1) begin
                            if (peek_mem_word(LAYOUT_Z0_BASE + phase_idx) !== t0_initial[phase_idx]) begin
                                fs_mu_z0_mismatch = fs_mu_z0_mismatch + 1;
                                if (fs_mu_first_z0 < 0) fs_mu_first_z0 = phase_idx;
                            end
                            if (peek_mem_word(LAYOUT_Z1_BASE + phase_idx) !== t1_initial[phase_idx]) begin
                                fs_mu_z1_mismatch = fs_mu_z1_mismatch + 1;
                                if (fs_mu_first_z1 < 0) fs_mu_first_z1 = phase_idx;
                            end
                        end
                        $display("  FS_SAMPLE_MU identity: z0_mismatch=%0d first=%0d z1_mismatch=%0d first=%0d",
                            fs_mu_z0_mismatch, fs_mu_first_z0, fs_mu_z1_mismatch, fs_mu_first_z1);
                        if (fs_mu_first_z0 >= 0) begin
                            $display("    first z0 mismatch: got=%h exp=%h",
                                peek_mem_word(LAYOUT_Z0_BASE + fs_mu_first_z0), t0_initial[fs_mu_first_z0]);
                        end
                        if (fs_mu_first_z1 >= 0) begin
                            $display("    first z1 mismatch: got=%h exp=%h",
                                peek_mem_word(LAYOUT_Z1_BASE + fs_mu_first_z1), t1_initial[fs_mu_first_z1]);
                        end
                    end
                    for (phase_idx = 0; phase_idx < 4; phase_idx = phase_idx + 1) begin
                        $display("    z0[%0d]=%h z1[%0d]=%h",
                            phase_idx, peek_mem_word(LAYOUT_Z0_BASE + phase_idx),
                            phase_idx, peek_mem_word(LAYOUT_Z1_BASE + phase_idx));
                        if ($test$plusargs("FS_SAMPLE_MU")) begin
                            $display("      t0[%0d]=%h t1[%0d]=%h",
                                phase_idx, peek_mem_word(LAYOUT_T0_BASE + phase_idx),
                                phase_idx, peek_mem_word(LAYOUT_T1_BASE + phase_idx));
                        end
                    end
                end
            end
        end
    end

    // ─── Main test sequence ───
    reg [31:0] sr;
    reg [31:0] cfg_word;
    integer    timeout;

    initial begin
        bus_cs    = 1'b0;
        bus_wr    = 1'b0;
        bus_addr  = 16'd0;
        bus_wdata = 32'd0;
        cfg_word  = 32'h00000004;
        timeout   = 0;
        s1_mismatch = 0;
        s2_mismatch = 0;

        // Wait for reset
        repeat (8) @(posedge clk);
        rst_n = 1'b1;
        repeat (4) @(posedge clk);

        $display("=== FalconSign Full Key Integration Test ===");
        $display("Loading key material into memory...");

        // ─── Step 1: Load B matrix (complex FFT data) ───
        // Software produces 256 complex words per B polynomial.
        // Hardware allocates 512 words per region; unused words stay zero.
        load_hex_to_mem("t0_target.hex", LAYOUT_T0_BASE, N_WORDS);
        load_hex_to_mem("t1_target.hex", LAYOUT_T1_BASE, N_WORDS);
        for (i = 0; i < N_WORDS; i = i + 1) begin
            t0_initial[i] = peek_mem_word(LAYOUT_T0_BASE + i);
            t1_initial[i] = peek_mem_word(LAYOUT_T1_BASE + i);
        end

        load_hex_to_mem("b00.hex", LAYOUT_B00_BASE, N_WORDS);
        load_hex_to_mem("b01.hex", LAYOUT_B01_BASE, N_WORDS);
        load_hex_to_mem("b10.hex", LAYOUT_B10_BASE, N_WORDS);
        load_hex_to_mem("b11.hex", LAYOUT_B11_BASE, N_WORDS);

        // ─── Step 2: Load LDL tree ───
        load_hex_to_mem("tree_full_poly.hex", LAYOUT_TREE_BASE, 2816);
        if ($test$plusargs("ZERO_TREE")) begin
            for (i = 0; i < 2816; i = i + 1) begin
                poke_mem_word(LAYOUT_TREE_BASE + i, 256'd0);
            end
            $display("ZERO_TREE: cleared tree image");
        end

        // ─── Step 3: Load public key h (NTT+Montgomery, packed uint16) ───
        load_hex_to_mem("h_ntt.hex", LAYOUT_H_BASE, 32);

        // ─── Step 4: Load expected hm (challenge c) for comparison ───
        load_hex_to_mem("hm.hex", LAYOUT_C_INT_BASE, 32);
        $readmemh("s1_expected.hex", s1_expected);
        $readmemh("s2_expected.hex", s2_expected);

        $display("All key material loaded.");

        // Quick verification: check first L10 value at tree_base
        $display("Tree check: word[%0d] = %h", LAYOUT_TREE_BASE, peek_mem_word(LAYOUT_TREE_BASE));
        // Expected: re=0xc015c20e7dd64500 im=0xc018938ffc21e1ad
        // 256-bit word: {64'd0, 64'd0, im, re}
        // = 0000000000000000_0000000000000000_c018938ffc21e1ad_c015c20e7dd64500

        // ─── Step 5: Configure hardware ───
        // cfg[0] = bypass_fs: skip ffSampling (use identity z=t)
        // cfg[1] = force_accept: skip rejection check (debug only)
        // cfg[2] = start_at_fs: use externally preloaded t0/t1/tree/B/h/hm
        // cfg[3] = dynamic_tree: scheduler emits LDL tasks (EXU TODO)
        if ($test$plusargs("BYPASS_FS")) begin
            cfg_word[0] = 1'b1;
            preload_bypass_z_eq_t();
        end
        if ($test$plusargs("FORCE_ACCEPT"))
            cfg_word[1] = 1'b1;
        if ($test$plusargs("START_AT_FS")) begin
            cfg_word[2] = 1'b1;
            // In this mode we start directly from FS/VD, so preload z=t
            // to keep the identity test clean. HP/FC won't run so t0 stays.
            preload_bypass_z_eq_t();
        end
        bus_write(REG_CFG, cfg_word);
        $display("Config REG_CFG=0x%08h", cfg_word);

        // ─── Step 6: Start signing ───
        $display("\nStarting signing operation...");
        bus_write(REG_CR, 32'h00000001);

        // ─── Step 7: Wait for completion ───
        while (!done && !fail && timeout < 25000000) begin
            @(posedge clk);
            timeout = timeout + 1;
        end

        // ─── Step 8: Check results ───
        bus_read(REG_SR, sr);
        $display("\n=== Results ===");
        $display("  done=%0d  fail=%0d  irq=%0d  status=0x%02h  sr=0x%08h",
            done, fail, bus_irq, status, sr);
        $display("  total_cycles=%0d  restarts=%0d  timeout=%0d",
            total_cycle, restart_cnt, timeout);
        $display("  FS counters: issues=%0d done=%0d fail=%0d sample_cmds=%0d sample_rsps=%0d",
            fs_task_issues, fs_task_done, fs_task_fail, sample_cmds, sample_rsps);
        $display("  FS debug: ts_run=%0d ts_state=%0d ts_busy=%0d ts_done=%0d ts_fail=%0d ts_status=%02x fe_state=%0d fe_op=%0d fe_task_ready=%0d",
            dut.u_ts.run_state, dut.u_ts.state_q, dut.ts_busy, dut.ts_done, dut.ts_fail, dut.ts_status,
            dut.u_fe.state, dut.u_fe.op_q, dut.fe_task_ready);
        $display("  Norm debug: accept=%0d norm_sq=%0d norm_status=0x%02h bound=%0d",
            dut.norm_accept, dut.norm_sq, dut.norm_status, dut.FALCON512_BOUND_SQ);

        $display("  Completed phases:");
        $display("    SH_SeedHash:     %s", completed_phases[1] ? "YES" : "NO");
        $display("    HP_HashToPoint:  %s", completed_phases[2] ? "YES" : "NO");
        $display("    FC_FFT:          %s", completed_phases[3] ? "YES" : "NO");
        $display("    FS_ffSampling:   %s", completed_phases[4] ? "YES" : "NO");
        $display("    VD_BhatMul:      %s", completed_phases[5] ? "YES" : "NO");
        $display("    IV_IFFT:         %s", completed_phases[6] ? "YES" : "NO");
        $display("    FI_FprToInt:     %s", completed_phases[7] ? "YES" : "NO");
        $display("    N1_NTT:          %s", completed_phases[8] ? "YES" : "NO");
        $display("    RC_RejCheck:     %s", completed_phases[9] ? "YES" : "NO");

        // ─── Step 9: Read back signature from memory ───
        // s2 is at LAYOUT_SIG_BASE after fpr_to_int16 conversion
        // s1 is at LAYOUT_S1_BASE after NTT computation
        if (done) begin
            $display("\n=== Reading signature from memory ===");
            $display("s2 (first 16 int16 values, at SIG_BASE=%0d):", LAYOUT_SIG_BASE);
            for (i = 0; i < 4; i = i + 1) begin
                $display("  word[%0d] = %h", i, peek_mem_word(LAYOUT_SIG_BASE + i));
            end
            $display("s1 (first 16 int16 values, at S1_BASE=%0d):", LAYOUT_S1_BASE);
            for (i = 0; i < 4; i = i + 1) begin
                $display("  word[%0d] = %h", i, peek_mem_word(LAYOUT_S1_BASE + i));
            end

            s1_mismatch = 0;
            s2_mismatch = 0;
            for (cmp_idx = 0; cmp_idx < 32; cmp_idx = cmp_idx + 1) begin
                if (peek_mem_word(LAYOUT_SIG_BASE + cmp_idx) !== s2_expected[cmp_idx]) begin
                    if (s2_mismatch < 8) begin
                        $display("  S2 mismatch[%0d]: got=%h exp=%h",
                            cmp_idx, peek_mem_word(LAYOUT_SIG_BASE + cmp_idx), s2_expected[cmp_idx]);
                    end
                    s2_mismatch = s2_mismatch + 1;
                end
                if (peek_mem_word(LAYOUT_S1_BASE + cmp_idx) !== s1_expected[cmp_idx]) begin
                    if (s1_mismatch < 8) begin
                        $display("  S1 mismatch[%0d]: got=%h exp=%h",
                            cmp_idx, peek_mem_word(LAYOUT_S1_BASE + cmp_idx), s1_expected[cmp_idx]);
                    end
                    s1_mismatch = s1_mismatch + 1;
                end
            end
            $display("Expected signature compare: S2 mismatches=%0d/32, S1 mismatches=%0d/32",
                s2_mismatch, s1_mismatch);
        end

        // ─── Final verdict ───
        if (done && !fail && s1_mismatch == 0 && s2_mismatch == 0) begin
            $display("\n======================================");
            $display("  TEST PASSED: Signing matched expected signature");
            $display("  Cycles: %0d  Phase count: %0d",
                total_cycle, phase_idx);
            $display("======================================");
        end else if (done && !fail) begin
            $display("\n======================================");
            $display("  TEST FAILED: Signing completed but signature mismatch");
            $display("  S2 mismatches: %0d/32", s2_mismatch);
            $display("  S1 mismatches: %0d/32", s1_mismatch);
            $display("======================================");
            $fatal(1);
        end else if (fail) begin
            $display("\n======================================");
            $display("  TEST FAILED: status=0x%02h", status);
            $display("  Phase at failure: %s", phase_name(dut.st));
            $display("======================================");
            $fatal(1);
        end else begin
            $display("\n======================================");
            $display("  TEST TIMEOUT at cycle %0d", timeout);
            $display("  Phase: %s (st=%0d sn=%0d)",
                phase_name(dut.st), dut.st, dut.sn);
            $display("======================================");
            $fatal(1);
        end

        #100;
        $finish;
    end

    // ─── Watchdog ───
    reg [31:0] wd_cnt;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            wd_cnt <= 0;
        else begin
            wd_cnt <= wd_cnt + 1;
            if (wd_cnt == 32'd10000000) begin
                $display("WATCHDOG at cycle=%0d phase=%s st=%0d sn=%0d",
                    wd_cnt, phase_name(dut.st), dut.st, dut.sn);
                $display("  SH: word_idx=%0d absorb=%0d",
                    dut.sh_word_idx, dut.shake_absorb);
                $display("  HP: coeff_cnt=%0d wr_addr=%0d",
                    dut.hp_coeff_cnt, dut.hp_wr_addr);
                $display("  Salt: cnt=%0d rc_fail=%0d",
                    dut.salt_cnt, dut.rc_fail);
                $display("  fs_sz_cmd_valid=%0d ready=%0d",
                    dut.fe_sz_cmd_valid, dut.fe_sz_cmd_ready);
                $finish;
            end
        end
    end

    // ─── VCD dump ───
    initial begin
        if ($test$plusargs("DUMP_VCD")) begin
            $dumpfile("tb_falconsign_top_fullkey.vcd");
            $dumpvars(0, tb_falconsign_top_fullkey);
        end
    end

endmodule
